DROP TABLE BOOK_LIST;
DROP TABLE LIST;
DROP TABLE BOOK_GENRE;
DROP TABLE GENRE;
DROP TABLE BOOK_AUTHOR;
DROP TABLE COMMENT;
DROP TABLE BOOK;
DROP TABLE PERIOD;
DROP TABLE AUTHOR;
DROP TABLE PUBLISHER;

CREATE TABLE PUBLISHER
(
	PublisherID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Name VARCHAR(150) NOT NULL,
	Founded VARCHAR(4), --2012
	Headquarters VARCHAR(150), --Random House Tower
	Location VARCHAR(150), --New York City
	Country VARCHAR(150), -- United States
	Distribution VARCHAR(150), --Worldwide
	OfficialWebsite VARCHAR(150), --www.random.com
);

CREATE TABLE AUTHOR(
	AuthorID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() not null,
	Name VARCHAR(50),
	Surname VARCHAR(50),
	Country VARCHAR(100)
);

CREATE TABLE PERIOD(
	PeriodID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(500) NOT NULL,
	Description VARCHAR(5000)
);

CREATE TABLE BOOK(
	BookID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	AuthorId UNIQUEIDENTIFIER REFERENCES AUTHOR(AuthorID),
	PublisherId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES PUBLISHER(PublisherID),
	PeriodId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES PERIOD(PeriodID),
	Title VARCHAR(5000) NOT NULL,
	Year INTEGER NOT NULL,
	Grade INTEGER,
	NumberOfPages INTEGER,
	OriginalLanguage VARCHAR(20),
	CountryOfOrigin VARCHAR(100),
	OriginalTitle VARCHAR(5000)
);

CREATE TABLE COMMENT
(
	CommentID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	BookId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES BOOK(BookID) ON DELETE CASCADE,
	Content VARCHAR(255) NOT NULL,
	NumberOfLikes INTEGER DEFAULT 0
);

CREATE TABLE BOOK_AUTHOR(
	AuthorId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AUTHOR(AuthorID),
	BookId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES BOOK(BookID),
	CONSTRAINT ID PRIMARY KEY (BookId,AuthorId)
);

CREATE TABLE GENRE(
	GenreID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(20)
);

CREATE TABLE BOOK_GENRE(
	BookId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES BOOK(BookID),
	GenreId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES GENRE(GenreID),
	CONSTRAINT BookGenreID PRIMARY KEY (BookId,GenreId)
);

CREATE TABLE LIST(
	ListID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(50),
	Description VARCHAR(200),
	NumberOfLikes INT default 0,
);

CREATE TABLE BOOK_LIST(
	BookId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES BOOK(BookID),
	ListId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES LIST(ListID) ON DELETE CASCADE,
	CONSTRAINT BookListID PRIMARY KEY (BookId,ListId)
);


/*inserti:
INSERT INTO Publisher(PublisherID, Name, Founded, Headquarters,Location, Country,Distribution, OfficialWebsite)
VALUES(default, 'Penguin Random House', '2013', 'Random House Tower', 'New York City', 'United States', 'WorldWide', 'penguinrandomhouse.com');

INSERT INTO AUTHOR(Name,Surname,Country) VALUES ('Franz','Kafka','Czechia');

INSERT INTO PERIOD (Name) VALUES ('20.stoljeæe');

INSERT INTO BOOK VALUES (default, 'E9776BF0-9190-47DF-8582-18649E6CE8C9', '19F3351B-0FF7-4B4E-918A-5B31AFFCE6AC',
'32461297-5E34-4BE2-9315-F52114B34775','Preobrazba',1915, 8.5, 100, 'german', 'Austria', 'Die Verwandlung');

INSERT INTO COMMENT VALUES (default, '31A30562-A238-4EFF-B103-D011F6188FFF', 'Super knjiga!',default)

INSERT INTO BOOK_AUTHOR VALUES ('E9776BF0-9190-47DF-8582-18649E6CE8C9', '31A30562-A238-4EFF-B103-D011F6188FFF');

INSERT INTO GENRE (Name) VALUES ( 'SF');
INSERT INTO GENRE (Name) VALUES ( 'Action');
INSERT INTO GENRE (Name) VALUES ( 'Comedy');
INSERT INTO GENRE (Name) VALUES ( 'Horror');
INSERT INTO GENRE (Name) VALUES ( 'Action');

INSERT INTO BOOK_GENRE VALUES ('31A30562-A238-4EFF-B103-D011F6188FFF', '16CD795B-B872-4C4F-902A-8F4DDB6A6D2C')

INSERT INTO LIST (Name, Description) VALUES ('Harry Potter and the prisoners of Azkaban', 'Third Harry Potter Book');

INSERT INTO BOOK_LIST VALUES ('31A30562-A238-4EFF-B103-D011F6188FFF', 'E96B4EEE-1A65-40BB-82E5-21050DE72AC1');
*/
